[project]
name = "astra-harness"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "astropy>=8.0.1",
    "astroquery>=0.4.11",
    "fastapi>=0.138.0",
    "httpx>=0.28.1",
    "numpy>=2.5.2",
    "tetra3",
    "uvicorn>=0.52.4",
    "websockets>=17.0.1",
    "pyserial>=3.5"
]

[tool.uv.sources]
tetra3 = { git = "https://github.com/esa/tetra3.git" }

[tool.ty]
ignore = ["astropy", "astroquery"]
